export type ListingStatus = 'pending' | 'approved' | 'expired' | 'rejected';
export type PaymentStatus = 'unpaid' | 'submitted' | 'paid';
export type ListingType = 'sale' | 'rent';
export type PosterType = 'individual' | 'company';

export type Listing = {
  id: string;
  user_id?: string;
  title: string;
  listing_type: ListingType;
  poster_type: PosterType;
  property_type: string;
  location: string;
  price: number;
  area: number;
  rooms: number;
  floor: number | null;
  built_year: number | null;
  door_type: string | null;
  window_type: string | null;
  has_certificate: boolean;
  description: string;
  phone: string;
  status: ListingStatus;
  image_url: string | null;
  extra_images?: string[] | null;
  expires_at: string | null;
  approved_at?: string | null;
  created_at: string;
  owner_name?: string | null;
  company_name?: string | null;
  company_register?: string | null;
  payment_status?: PaymentStatus | null;
  payment_amount?: number | null;
  payment_sender_name?: string | null;
  payment_reference?: string | null;
  payment_submitted_at?: string | null;
  paid_at?: string | null;
};